### ISSUE TITLE
doesn't decrypt

### ISSUE THREAD

**Issue by LoftyCode2** [Michel-M-code/Metadata-Decryptor#11]
The script stopped decrypting metadata 0.32.3 
DECRYPTION FAILED!

**Comment by Michel-M-code** [comment]
First of all, decrypt the version before this one, and use the decrypted metadata as a reference. Second of all, I've published a fix for another issue, go and update the script.

**Comment by LoftyCode2** [comment]
I downloaded the latest new version of the decryptor and it still doesn't work @Michel-M-code 

![Image](https://github.com/user-attachments/assets/bc130bc6-3a59-4627-9845-397d2aef80af)

**Comment by Michel-M-code** [comment]
Did you read the first sentence? You need to decrypt 0.32.2 and use that decrypted metadata as the input reference file for 0.32.3

**Comment by LoftyCode2** [comment]
thank you all
